# Generated by Django 5.2.16 on 2026-08-06 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_change_category_to_foreignkey'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='name_en',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='English Name'),
        ),
    ]
